/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import br.com.Controle.ControleSorteio;
import br.com.conexao.Conexao;
import br.com.model.bean.Sorteio;
import java.sql.SQLException;

/**
 *
 * @author yargorodrigues
 */
public class TelaSorteio extends javax.swing.JFrame {
    Sorteio sort = new Sorteio();
    /**
     * Creates new form TelaSorteio
     */
    public TelaSorteio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cont = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtEnd = new javax.swing.JTextField();
        txtReg = new javax.swing.JTextField();
        JbSorteio = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SorteioPDV");
        getContentPane().setLayout(null);

        Cont.setBackground(new java.awt.Color(51, 0, 51));
        Cont.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        Cont.setForeground(new java.awt.Color(255, 255, 255));
        Cont.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(Cont);
        Cont.setBounds(820, 30, 90, 60);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome PDV:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 390, 330, 58);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cidade:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 450, 290, 58);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bairro:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 570, 280, 58);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Endereço:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 510, 320, 58);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Regional:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(270, 630, 310, 58);

        txtCod.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        getContentPane().add(txtCod);
        txtCod.setBounds(600, 340, 370, 40);

        txtNome.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        getContentPane().add(txtNome);
        txtNome.setBounds(600, 400, 950, 40);

        txtCidade.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        getContentPane().add(txtCidade);
        txtCidade.setBounds(600, 460, 950, 40);

        txtBairro.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        getContentPane().add(txtBairro);
        txtBairro.setBounds(600, 580, 950, 40);

        txtEnd.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        getContentPane().add(txtEnd);
        txtEnd.setBounds(600, 520, 950, 40);

        txtReg.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        getContentPane().add(txtReg);
        txtReg.setBounds(600, 650, 490, 40);

        JbSorteio.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        JbSorteio.setText("Sorteio");
        JbSorteio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbSorteioActionPerformed(evt);
            }
        });
        getContentPane().add(JbSorteio);
        JbSorteio.setBounds(1820, 1010, 95, 29);

        jLabel8.setBackground(new java.awt.Color(51, 0, 51));
        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Código PDV:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 330, 340, 58);

        jLabel9.setBackground(new java.awt.Color(51, 0, 51));
        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Código PDV:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 330, 340, 58);

        jLabel10.setBackground(new java.awt.Color(51, 0, 51));
        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Giro PDV");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(920, 30, 280, 58);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/BackREal.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        setSize(new java.awt.Dimension(1920, 1102));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JbSorteioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbSorteioActionPerformed
        // TODO add your handling code here:
        apertarBotao();
        SorteioId();
        Mostrar();
      
        txtCod.setText(String.valueOf(id));
        txtNome.setText(nome);
        txtCidade.setText(cidade);
        txtBairro.setText(bairro);
        txtEnd.setText(endereco);
        txtReg.setText(PegaRegional);
        
        salvarDadosBD();
        
       
        
    }//GEN-LAST:event_JbSorteioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSorteio().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cont;
    private javax.swing.JButton JbSorteio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtReg;
    // End of variables declaration//GEN-END:variables
    
    int sorteio_id;
    int id, pegaReg;
    String nome, cidade, endereco, bairro, telefone;
    String PegaRegional;

    private void SorteioId() {
         try {
            Conexao.executaSQL("select id_pdv from pdvs order by rand() limit 1");
            while (Conexao.rs.next()) {
                sorteio_id = Conexao.rs.getInt("id_pdv");
            }

            System.out.println("Id Sorteiado: " + sorteio_id);

        } catch (SQLException ex) {
            System.out.println("Erro ao executar o sorteio!" + ex);
        }


    }

    private void Mostrar() {
        try {
            Conexao.executaSQL("select * from pdvs where id_pdv ='" + sorteio_id + "'");
            while (Conexao.rs.next()) {
                id = Conexao.rs.getInt("id_pdv");
                nome = Conexao.rs.getString("nome_pdv");
                cidade = Conexao.rs.getString("cidade_pdv");
                bairro = Conexao.rs.getString("bairro");
                endereco = Conexao.rs.getString("endereco");
                pegaReg = Conexao.rs.getInt("id_regional");
                telefone = Conexao.rs.getString("telefone");
                pegarNomeRegional(String.valueOf(pegaReg));
                

                //JOptionPane.showMessageDialog(null, "Código PDV: "+ id +"\n"+ "Nome PDV: "+ nome +"\n"+ "Cidade: "+cidade+"\n"+
                //"Endereço: " + endereco+"\n"+ "Regional: " + PegaRegional);
            }
        } catch (SQLException ex) {

        }

    }
    
    public String pegarNomeRegional(String sql) {
        try {
            Conexao.executaSQL("select * from regional where id_regional ='" + sql + "'");
            
            while (Conexao.rs.next()) {
                PegaRegional = Conexao.rs.getString("nome_regional");
                System.out.println(PegaRegional);
            }

        } catch (SQLException ex) {
            System.out.println("Erro ao buscar nome regional");
        }
        return PegaRegional;

    }

    private void salvarDadosBD() {
        
            sort.setIdPdv_Sorteio(Integer.parseInt(txtCod.getText()));
            sort.setPdv_NomeSorteio(txtNome.getText());
            sort.setCidadeSorteio(txtCidade.getText());
            sort.setEnderecoSorteio(txtEnd.getText());
            sort.setRegionalSorteio(txtReg.getText());
            sort.setBairro(txtBairro.getText());
            sort.setTelefone(telefone);
            
            
            ControleSorteio.GravaDadosSorteio(sort);
            
        
        
    }
    int contador = 0;
    public void apertarBotao(){
        Cont.setText(String.valueOf(++contador+"º"));
        
    }

   
}
