/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import br.com.Controle.ControleCadastro;
import br.com.conexao.Conexao;
import br.com.model.bean.CadastroPdv;
import java.sql.SQLException;
import javax.swing.JComboBox;

/**
 *
 * @author Yargo Rodrigues
 */
public final class TelaCadPdv extends javax.swing.JDialog {
    
    int regional_id;
    CadastroPdv cadpdv = new CadastroPdv();

    /**
     * Creates new form TelaCadPdv
     * @param parent
     * @param modal
     */
    public TelaCadPdv(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        Conexao.getConnection();
        initComponents();
        carregarRegional();
        
        
    }
    
    public void carregarRegional() {
        // metodo que busca as regionais cadastras na talela regional, e carrega os seu nome no Combobox
        
        try {
            ComboRegional.removeAllItems();
            Conexao.executaSQL("select * from regional");
            while (Conexao.rs.next()) {
                ComboRegional.addItem(Conexao.rs.getString("nome_regional"));
            }
            pegarIdRegional(ComboRegional.getSelectedItem().toString());
        } catch (Exception e) {
            
        }
        
    }
    
    private void pegarIdRegional(String sql) {
        // metodo que converte o nome da regional cadastra na tabela regional em seu id, fazendo a relacao com a tabela pdvs
        try {
            Conexao.executaSQL("select * from regional where nome_regional ='" + sql + "'");
            while (Conexao.rs.next()) {
                regional_id = Conexao.rs.getInt("id_regional");
               
            }
            
        } catch (SQLException ex) {
            
        }
    }
    
    private void salvarDados() {
        // importacao do metodo salvarDados que esta na classe ControleCadastro
        cadpdv.setId(Integer.parseInt(jCod_pdv.getText()));
        cadpdv.setNome_pdv(jNome_Pdv.getText());
        cadpdv.setEndereco(jEnd_Pdv.getText());
        cadpdv.setBairro(txtBairro.getText());
        cadpdv.setTelefone(jTelefone.getText());
        cadpdv.setId_regional(regional_id);
        cadpdv.setRota(Integer.parseInt(jRota.getText()));
        cadpdv.setCidade(txtCidade.getText());

        ControleCadastro.gravarDados(cadpdv);
        
        // após salvar os dados, limpa todos os campos
        jCod_pdv.setEnabled(false);
        jNome_Pdv.setEnabled(false);
        jEnd_Pdv.setEnabled(false);
        txtCidade.setEnabled(false);
        jTelefone.setEnabled(false);
        jRota.setEnabled(false);
        txtBairro.setEnabled(false);
        
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JSalvarPDV = new javax.swing.JButton();
        jTelefone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboRegional = new javax.swing.JComboBox<>();
        jNovoCad = new javax.swing.JButton();
        jCod_pdv = new javax.swing.JFormattedTextField();
        jBtSairPDV = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCidade = new javax.swing.JLabel();
        jRota = new javax.swing.JFormattedTextField();
        jNome_Pdv = new javax.swing.JTextField();
        jEnd_Pdv = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Pontos de Vendas - SorteioPDV");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Código PDV: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome PDV: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Endereço: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bairro: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Telefone: ");

        JSalvarPDV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JSalvarPDV.setText("Salvar");
        JSalvarPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSalvarPDVActionPerformed(evt);
            }
        });

        try {
            jTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Regional:");

        ComboRegional.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComboRegionalPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        ComboRegional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRegionalActionPerformed(evt);
            }
        });

        jNovoCad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jNovoCad.setText("Novo");
        jNovoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoCadActionPerformed(evt);
            }
        });

        jCod_pdv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jCod_pdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCod_pdvActionPerformed(evt);
            }
        });

        jBtSairPDV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtSairPDV.setText("Sair");
        jBtSairPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairPDVActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setText("Rota: ");

        jCidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCidade.setText("Cidade: ");

        jRota.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCod_pdv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(ComboRegional, 0, 218, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jCidade))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNome_Pdv)
                            .addComponent(jEnd_Pdv)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(txtCidade))
                                .addGap(43, 43, 43)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRota, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jNovoCad)
                .addGap(18, 18, 18)
                .addComponent(JSalvarPDV)
                .addGap(18, 18, 18)
                .addComponent(jBtSairPDV)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(ComboRegional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCod_pdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jNome_Pdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jEnd_Pdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCidade)
                    .addComponent(jRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JSalvarPDV)
                    .addComponent(jNovoCad)
                    .addComponent(jBtSairPDV))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(637, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JSalvarPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSalvarPDVActionPerformed
        salvarDados();
      

    }//GEN-LAST:event_JSalvarPDVActionPerformed

    private void ComboRegionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRegionalActionPerformed

    }//GEN-LAST:event_ComboRegionalActionPerformed

    private void jCod_pdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCod_pdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCod_pdvActionPerformed

    private void jBtSairPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairPDVActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtSairPDVActionPerformed

    private void ComboRegionalPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboRegionalPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        pegarIdRegional(ComboRegional.getSelectedItem().toString());
    }//GEN-LAST:event_ComboRegionalPopupMenuWillBecomeInvisible

    private void jNovoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoCadActionPerformed
        // TODO add your handling code here:
        Conexao.getConnection();
        jCod_pdv.setText("");
        jNome_Pdv.setText("");
        jEnd_Pdv.setText("");
        txtCidade.setText("");
        jTelefone.setText("");
        jRota.setText("");
        txtBairro.setText("");
        
        jCod_pdv.setEnabled(true);
        jNome_Pdv.setEnabled(true);
        jEnd_Pdv.setEnabled(true);
        txtCidade.setEnabled(true);
        jTelefone.setEnabled(true);
        jRota.setEnabled(true);
        txtBairro.setEnabled(true);
    }//GEN-LAST:event_jNovoCadActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadPdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadPdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadPdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadPdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaCadPdv dialog = new TelaCadPdv(new javax.swing.JFrame(), true);
            dialog.dispose();
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    //System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> ComboRegional;
    private javax.swing.JButton JSalvarPDV;
    private javax.swing.JButton jBtSairPDV;
    private javax.swing.JLabel jCidade;
    private javax.swing.JFormattedTextField jCod_pdv;
    private javax.swing.JTextField jEnd_Pdv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNome_Pdv;
    private javax.swing.JButton jNovoCad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jRota;
    private javax.swing.JFormattedTextField jTelefone;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    // End of variables declaration//GEN-END:variables

    
}
